### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by WhatevvsDev** [stefanpgd/BYTE#1]
I cloned the repository, but I can't seem to build the project as it doesn't exist

**Comment by stefanpgd** [comment]
Dear @WhatevvsDev, the most recent commit on the branch `main` should resolve this issue. Thank you for the heads up. 👍

**Comment by thepaladon** [comment]
No. 
Bad GitHub usage.
 I rate you **Poor** on your `ILO 2.3`. You should close the commit which fixes the issue is here. Ideally that should be done on another branch and with a PR which closes this issue automatically. 
 
 git bozo
 git l
 git clownery
