### ISSUE TITLE
Closes immediately

### ISSUE THREAD

**Issue by WhatevvsDev** [stefanpgd/BYTE#3]
Whenever I run the project it closes immediately instead of doing anything, is this intended behavior?

**Reproduction steps:**
1. Run project

**Expected behavior:**
1. Project runs until I close it

**Observed behavior:**
1. Project closes instantly

**Comment by thepaladon** [comment]
I've had this issue as well and haven't figured out how to fix it.

**Comment by stefanpgd** [comment]
I've resolved this issue by implementing an SDL2 event processing loop. The program can now run until a quit event has been received by the application. Thank you for finding the issue.

**Comment by thepaladon** [comment]
'Bout time.

**Comment by stefanpgd** [comment]
We're trying our best sir.

**Comment by stefanpgd** [comment]
:(
